### ISSUE TITLE
Failed to resolve : Cards.pay:paycardsrecognizer:1.0.0

### ISSUE THREAD

**Issue by harikrishnanajay** [faceterteam/PayCards_Android#17]
Dear team,
 We have tried the code you mentioned by seems we are getting the error mentioned. Could you please help me to fix this.
![photo-2018-07-23-19-53-21](https://user-images.githubusercontent.com/41582779/43083036-28de0644-8eb3-11e8-88f5-68ccd311af6a.jpg)

**Comment by SemenovAlexander** [comment]
Same issue

**Comment by alexey0xdc** [comment]
The problem with the repository availability has been fixed

**Comment by islamassi** [comment]
Same issue.
