### ISSUE TITLE
pay.cards SDK having issue while integrating

### ISSUE THREAD

**Issue by Sathish2911** [faceterteam/PayCards_Android#18]
Dear team,

while integrating the pay cards SDK (from website pay.cards) we are getting an error which is attached. please have and look and support us to solve the issue and to integrate paycards in our mobile app

email id: reginaldo@rashidaljabrigroup.com
![43083036-28de0644-8eb3-11e8-88f5-68ccd311af6a](https://user-images.githubusercontent.com/41688894/43203556-a01df908-902f-11e8-8069-397f15ff8ee7.jpg)

**Comment by rafaelwinter** [comment]
If you are in a hurry like I was, I recommend you putting the _sdk_ folder with your code, and configure gradle to handle it as a dependency. This isn't good, but at least you can get it running. The rest of the integration is quite easy, take a look at the Demo sources.
