### ISSUE TITLE
Failed to resolve : Cards.pay:paycardsrecognizer:1.0.0

### ISSUE THREAD

**Issue by Shadwild** [faceterteam/PayCards_Android#30]
Hello
I can not build a project.

> ERROR: Failed to resolve: cards.pay:paycardsrecognizer:1.0.0

Repository https://pay.cards/maven/  - 403 Forbidden

**Comment by nsekhar90** [comment]
Same problem

**Comment by tommybuonomo** [comment]
Same !

**Comment by nsekhar90** [comment]
can @alexey0xdc or @vitkuzmenko help ?

**Comment by AyatKhraisat** [comment]
same problem

**Comment by eduhrcastro** [comment]
same problem

**Comment by josechagas** [comment]
Same problem

**Comment by leijdekkers** [comment]
Is there an alternative in case the library is not downloadable anymore?

**Comment by MATPOCKIH** [comment]
Try to use dependency
implementation 'cards.pay:paycardsrecognizer:1.1.0'

**Comment by TaslimOseni** [comment]
In my case, I forgot to add the `url "http://pay.cards/maven"` to my project's build.gradle.

**Comment by TaslimOseni** [comment]
In my case, I forgot to add the `url "http://pay.cards/maven"` to my project's build.gradle.

**Comment by Gusstavo1** [comment]
same problem 

implementation 'cards.pay:paycardsrecognizer:1.1.1'

**Comment by VValkyrie** [comment]
+1

same problem

**Comment by colossusmk2** [comment]
Same problem: 
> Could not resolve cards.pay:paycardsrecognizer:1.1.0
