### ISSUE TITLE
Not Scanning all the cards

### ISSUE THREAD

**Issue by Chandrakala14** [faceterteam/PayCards_Android#4]
Hi,

Nice Effort.
It is working for some cards only, Is there any enhancement  ?

**Comment by tchernitski** [comment]
The SDK supports 16 digits embossed Visa/MasterCard cards, if you have other 16 digits embossed  cards and number not started with 4(Visa) or 55/56(MasterCard), then please update CNumberRecognizer::CheckSum method according to your need
