### ISSUE TITLE
What is status quo of this project? Is it  deprecated, abandoned or just postponed?

### ISSUE THREAD

**Issue by piotrek1543** [faceterteam/PayCards_Android#51]
Hi,

I do not see any update from two years, so I need to ask you if this project is still maintained or deprecated? 

Some changes like adding new card types like AmEx, adding more fonts to recognize or more view customization would be great improvement for that library, which is basically very good.

Have a nice day,
Piotr

**Comment by pcrds** [comment]
Hi there. The most correct will be to say that Pay.Cards is currently postponed bacause all the efforts are focused on faceter. 

If there is someone who want's to join the project and contribute/maintail the project - feel free to ask

**Comment by piotrek1543** [comment]
@pcrds  thanks for response. I am closing this for now.
