### ISSUE TITLE
Other card type recognization

### ISSUE THREAD

**Issue by khanhbkqt** [faceterteam/PayCards_Android#7]
I'm developing an app for other card.
It has its own card but the number doesn't fit numberWindowRect.
I tried to change the coordinates but it still doesn't work.

Could you please give me some information about the variables in your recognize classes?

**Comment by tchernitski** [comment]
numberWindowRect is region of interest where the whole number is. The coordinates of numberWindowRect are relative to the 960x660 box (captured and aligned card image).  numberWindowRect is used to localize Y position of the number. Then we crop numberWindowRect at top and bottom using digits height (hardcoded digitSize) and Y position we got from previous step. Then areaX0, areaX1, areaX2, areaX3 ROIs are used to localize X position of each digit blocks areaX0..3 coordinates are relative to the ROI we got after cropping in previous step.

I assume you should use photo-editing software to crop your card and resize it to 960x660 then you can measure your own ROIs.

**Comment by khanhbkqt** [comment]
Thank you for replying.
In your code
`static const cv::Rect numberWindowRect(54,221,552,60);`

So I can calculate the card width: 552 + 2x54 = 660
But you said the card size is 960x660?

**Comment by tchernitski** [comment]
I am sorry correct size is Size(660,416)
https://github.com/faceterteam/PayCards_iOS_Source/blob/3a340383da7b4874489b44a7ed2cee3dec2efb18/PayCardsRecognizer/CrossPlatform/Recognizer/FrameStorage.cpp#L16

**Comment by khanhbkqt** [comment]
Thank you,

I just want to clarify some points:
1. What are these variables used for?
`static int panDigitPaddingX = 2;
static int panDigitPaddingY = 2;
static const int spaceBWDidits = 3;`
2. The numberWindowRect's height is 60, but why the digit height is only 37?

3. Where is the font setting? Currently our card number uses another font.

Thank you

**Comment by tchernitski** [comment]
> What are these variables used for?
> static int panDigitPaddingX = 2; static int panDigitPaddingY = 2; static const int spaceBWDidits = 3;

these constants used to split digit block XXXX to separate digits
https://github.com/faceterteam/PayCards_iOS_Source/blob/3a340383da7b4874489b44a7ed2cee3dec2efb18/PayCardsRecognizer/CrossPlatform/Recognizer/NumberRecognizer.cpp#L131

> The numberWindowRect's height is 60, but why the digit height is only 37?

numberWindowRect size is not exact size, we just assume that the number is somewhere in this area, than we localize accurate Y coordinate of number and Xs coordinates of digit blocks
![exml](https://user-images.githubusercontent.com/818062/32318717-1cbf2618-bfc9-11e7-9c1a-ac87abb95bc4.png)

> Where is the font setting? Currently our card number uses another font.

there is no font settings, neural network are used to recognise the digits. Images of embossed digits are used to train neural network. If digits on your card has other font or/and they are printed and not embossed then recognition accuracy will be worse. For better results you will need to retrain NN using your samples.
